---
title: "national-viewer"
output:
  flexdashboard::flex_dashboard:
    orientation: rows
    logo: logo.svg
    theme: bootstrap
    source_code: "https://github.com/hesscl/natrent-viewer"
---

```{r setup, include=FALSE}
library(yaml)
library(flexdashboard)
library(tidyverse)
library(lubridate)
library(sf)
library(sqldf)
library(plotly)
library(DT)
library(zoo)
library(tigris)

options(tigris_class = "sf")

#store credentials at base dir of UDrive (H:/) as YAML
cred <- read_yaml("H:/natrent0.yaml")

#connect to natrent0 using loaded credentials
DB <- dbConnect(RPostgres::Postgres(),
                dbname = "natrent",
                host = "natrent0.csde.washington.edu",
                port = 5432, 
                user = names(cred),
                password = cred[[names(cred)]],
                bigint = "integer")

clean_tbl <- tbl(DB, "clean") #clean listing table
cbsa_tbl <- tbl(DB, "cbsa")
fmr_tbl <- tbl(DB, "fmr")
```

Home {data-icon="fa-home"}
=====================================

Row
-------------------------------------

### N per day time-series

```{r}
today <- Sys.Date()

n_ts <- clean_tbl %>%
  filter(listingDate >= "2019-01-01", listingDate < today, !is.na(STATEFP10)) %>%
  group_by(listingDate) %>%
  tally %>%
  arrange(listingDate) %>%
  collect

plot_ly(n_ts, x = n_ts$listingDate, y = n_ts$n) %>%
  add_trace(type = "scatter", mode = "lines+markers")
```


Row
-------------------------------------

### ACS FMR versus Craigslist FMR for Counties in Top 100 MSAs
```{r}
#studios
fmr_cty_0B <- clean_tbl %>%
  filter(listingDate >= "2019-01-01", 
         !is.na(cleanRent), !is.na(cleanBeds), listingDate < today, !is.na(COUNTYFP10), 
         cleanBeds == 0) %>%
  group_by(STATEFP10, COUNTYFP10, cleanBeds) %>%
  summarize(n0B = n(),
            cl_fmr = quantile(cleanRent, .40)) %>%
  left_join(fmr_tbl) %>%
  rename(fmr = fmr0B) %>%
  select(STATEFP10, COUNTYFP10, cleanBeds, fmr, cl_fmr) %>%
  collect()

fmr_cty_1B <- clean_tbl %>%
  filter(listingDate >= "2019-01-01", 
         !is.na(cleanRent), !is.na(cleanBeds), listingDate < today, !is.na(COUNTYFP10), 
         cleanBeds == 1) %>%
  group_by(STATEFP10, COUNTYFP10, cleanBeds) %>%
  summarize(n1B = n(),
            cl_fmr = quantile(cleanRent, .40)) %>%
  left_join(fmr_tbl) %>%
  rename(fmr = fmr1B) %>%
  select(STATEFP10, COUNTYFP10, cleanBeds, fmr, cl_fmr) %>%
  collect()

fmr_cty_2B <- clean_tbl %>%
  filter(listingDate >= "2019-01-01", 
         !is.na(cleanRent), !is.na(cleanBeds), listingDate < today, !is.na(COUNTYFP10), 
         cleanBeds == 2) %>%
  group_by(STATEFP10, COUNTYFP10, cleanBeds) %>%
  summarize(n2B = n(),
            cl_fmr = quantile(cleanRent, .40)) %>%
  left_join(fmr_tbl) %>%
  rename(fmr = fmr2B) %>%
  select(STATEFP10, COUNTYFP10, cleanBeds, fmr, cl_fmr) %>%
  collect()

fmr_cty_3B <- clean_tbl %>%
  filter(listingDate >= "2019-01-01", 
         !is.na(cleanRent), !is.na(cleanBeds), listingDate < today, !is.na(COUNTYFP10), 
         cleanBeds == 3) %>%
  group_by(STATEFP10, COUNTYFP10, cleanBeds) %>%
  summarize(n3B = n(),
            cl_fmr = quantile(cleanRent, .40)) %>%
  left_join(fmr_tbl) %>%
  rename(fmr = fmr3B) %>%
  select(STATEFP10, COUNTYFP10, cleanBeds, fmr, cl_fmr) %>%
  collect()

fmr_cty_4B <- clean_tbl %>%
  filter(listingDate >= "2019-01-01", 
         !is.na(cleanRent), !is.na(cleanBeds), listingDate < today, !is.na(COUNTYFP10), 
         cleanBeds == 4) %>%
  group_by(STATEFP10, COUNTYFP10, cleanBeds) %>%
  summarize(n4B = n(),
            cl_fmr = quantile(cleanRent, .40)) %>%
  left_join(fmr_tbl) %>%
  rename(fmr = fmr4B) %>%
  select(STATEFP10, COUNTYFP10, cleanBeds, fmr, cl_fmr) %>%
  collect()

fmr_cty <- rbind(fmr_cty_0B, fmr_cty_1B, fmr_cty_2B, fmr_cty_3B, fmr_cty_4B)


fmr_cty_gg <- ggplot(fmr_cty, aes(x = fmr, y = cl_fmr, frame = cleanBeds)) +
  geom_smooth() +
  geom_abline(slope = 1, intercept = 0) +
  theme_minimal()

ggplotly(fmr_cty_gg)
```



Metro
=====================================

### Rent Distribution

```{r}
metro_sum <- clean_tbl %>%
  filter(listingDate >= "2018-01-01", !is.na(COUNTYFP10)) %>%
  left_join(cbsa_tbl, by = c("STATEFP10", "COUNTYFP10")) %>%
  group_by(cbsaName) %>%
  summarize(n = n(),
            rent_q05 = quantile(cleanRent, .05),
            rent_q25 = quantile(cleanRent, .25),
            rent_q50 = quantile(cleanRent, .5),
            rent_q75 = quantile(cleanRent, .75),
            rent_q95 = quantile(cleanRent, .95)) %>% 
  filter(!is.na(rent_q50), n >= 1000) %>%
  arrange(desc(n)) %>%
  collect

#ggplot(metro_sum, aes(x = ))

DT::datatable(metro_sum, options = list(pageLength = 100))
```


















